name: TestFlight
on: [pull_request]
jobs:
  test_job:
    name: Push to TestFlight
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install CocoaPod dependencies
        run: pod install
      # - name: Install gpg
      #   run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      # - name: mkdir
      #   run: mkdir build
      - name: Archive app
        run: xcodebuild -workspace BraintreeDropIn.xcworkspace -scheme DropInDemo -sdk iphoneos -configuration Release archive -allowProvisioningUpdates -archivePath $PWD/build/DropInDemo.xcarchive
      - name: make ipa
        run: xcodebuild -exportArchive -allowProvisioningUpdates -archivePath build/DropInDemo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/DropInDemo.ipa
      # - name: 'Upload app to TestFlight'
      #   uses: apple-actions/upload-testflight-build@v1
      #   with: 
      #     app-path: 'build/DropInDemo.ipa'
      #     app-type: 'ios'
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}