name: TestFlight
on: [pull_request]
jobs:
  test_job:
    name: Push to TestFlight
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Create ipa
        - run: mkdir build
        - run: xcodebuild -workspace BraintreeDropIn.xcworkspace -scheme DropInDemo -sdk iphoneos -configuration Release archive -archivePath build/DropInDemo.xcarchive
        - run: xcodebuild -exportArchive -allowProvisioningUpdates -archivePath build/DropInDemo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/DropInDemo.ipa
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with: 
          app-path: 'build/DropInDemo.ipa'
          app-type: 'ios'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}